api_platform:
    title: Shop API
    version: 0.1.1
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header
    mapping:
        paths: ['%kernel.project_dir%/config/packages/api_platform/resources']